# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: java

jdk:
  - openjdk8

#don't build tags
branches:
  except:
  - /^v\d/

#Below skips the installation step completely
install: skip

script:
  - >
    ./gradlew build publishToMavenLocal --scan
    && if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ];
      then ./gradlew publishToSonatype closeAndReleaseStagingRepository --scan; fi